### ISSUE TITLE
--no-fork

### ISSUE THREAD

**Issue by hgshoemaker** [scudre/alarm-central-station-receiver#1]
Raspberry Pi 3 Jessie MagicJack Silver.
when i try to use the --no-fork argument it returns an error   
tjapi = ctypes.CDLL("libtjapi.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtjapi.so: cannot open shared object file: No such file or directory

I cannot find this library

**Comment by scudre** [comment]
This issue is fixed now.  I forgot to include the library originally in the python package.
