### ISSUE TITLE
MagicJack Hardware Version?

### ISSUE THREAD

**Issue by gerrymanley** [scudre/alarm-central-station-receiver#8]
Hi,
Nice project you are working on and I would like to test it out. Just wondering if this is the version magicJack your purchased: http://www.magicjack.com/index.html

/Gerry Manley

**Comment by scudre** [comment]
I built this project using the original sliver one.  In this picture its the one in the top right hand side:
http://i.ebayimg.com/images/i/232582489043-0-1/s-l1000.jpg

You can find them on eBay for under $10 if you search around for 'Magicjack original'.
